### ISSUE TITLE
切换table 后报错

### ISSUE THREAD

**Issue by awennnnn** [code-farmer-i/el-table-editabled#1]
2个不同的接口按钮,我相互点击切换, 就报了地下的这个错误

vue.esm.js:591 [Vue warn]: Error in event handler for "click": "TypeError: Cannot read property '_states' of undefined"

found in

---> <ElButton>
       <ElTooltip>
         <ElTableEditabledCell> at node_modules\el-table-editabled\src\el-table-editabled-cell.vue
           <ElTableBody>
             <ElTable>
               <ElTableEditabled> at node_modules\el-table-editabled\src\el-table-editabled.vue
                 <ElDialog>
                   <List> at src\views\taskMange\list.vue
                     <AppMain> at src\views\layout\components\AppMain.vue
                       <Layout> at src\views\layout\Layout.vue
                         <App> at src\App.vue
                           <Root>
warn @ vue.esm.js:591
logError @ vue.esm.js:1737
globalHandleError @ vue.esm.js:1732
handleError @ vue.esm.js:1721
Vue.$emit @ vue.esm.js:2540
handleClick @ element-ui.common.js:9715
invoker @ vue.esm.js:2027
fn._withTask.fn._withTask @ vue.esm.js:1826
vue.esm.js:1741 TypeError: Cannot read property '_states' of undefined
    at table-store.js:53
    at Array.forEach (<anonymous>)
    at TableStore.setRowsStates (table-store.js:53)
    at VueComponent.editRows (el-table-editabled.vue?2c73:115)
    at VueComponent.handleEditRow (list.vue?79ac:771)
    at click (list.vue?1823:892)
    at VueComponent.invoker (vue.esm.js:2027)
    at VueComponent.Vue.$emit (vue.esm.js:2538)
    at VueComponent.handleClick (element-ui.common.js:9715)
    at invoker (vue.esm.js:2027)

**Comment by code-farmer-i** [comment]
场景描述不够清晰，定位不到问题啊

**Comment by awennnnn** [comment]
就是  我这里有2个按钮,查询员工任务与 设置部门任务 ,当我来回切换的时候,我在点击操作 底下的 编辑, 就报了 那个错误了...  方便加QQ 问吗?




------------------ 原始邮件 ------------------
发件人: "code-farmer-i"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 下午4:49
收件人: "code-farmer-i/el-table-editabled"<el-table-editabled@noreply.github.com>; 
抄送: "(&#x328;&#x321; &#x203E;&#x1DC4;&#x15E3;&#x203E;&#x1DC5; )&#x327;&#x322;"<294184921@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [code-farmer-i/el-table-editabled] 切换table 后报错 (#1)




场景描述不够清晰，定位不到问题啊

**Comment by code-farmer-i** [comment]
672247608
