### ISSUE TITLE
当编辑单元存在select时表单验证出现问题

### ISSUE THREAD

**Issue by zsh815** [code-farmer-i/el-table-editabled#2]
select验证一旦通过，validate或者validate rows的valid都为true

**Comment by code-farmer-i** [comment]
问题描述不清晰。。

**Comment by zsh815** [comment]
row中包含el-select，当这个el-select选择了option，row里面的其他编辑单元的验证规则都没有生效，直接返回true

**Comment by code-farmer-i** [comment]
能贴下代码吗

**Comment by zsh815** [comment]
抱歉，内网环境没法贴代码。我再研究研究吧
